name: ServerBackupPlugin
version: '2.0.0'
main: com.serverbackup.ServerBackupPlugin
api-version: '1.21'
author: ffurkandemir
description: Advanced backup system with integrations (CoreProtect, WorldGuard, PlaceholderAPI, etc.)
website: https://github.com/ffurkandemir/minecraft-server-backup-plugin
softdepend: [CoreProtect, WorldGuard, LuckPerms, PlaceholderAPI, Vault]

commands:
  backup:
    description: Create a backup of the server
    usage: /backup [now|auto|cancel]
    permission: serverbackup.backup
    aliases: [sb, backupnow]
  backuplist:
    description: List all available backups
    usage: /backuplist
    permission: serverbackup.list
    aliases: [listbackups, bl]
  backupsize:
    description: Show backup statistics and disk usage
    usage: /backupsize
    permission: serverbackup.list
    aliases: [bsize, backupstats]
  backuprestore:
    description: Restore from a backup
    usage: /backuprestore <backup-name>
    permission: serverbackup.restore
    aliases: [restore]
  backupdelete:
    description: Delete a specific backup
    usage: /backupdelete <backup-name>
    permission: serverbackup.delete
    aliases: [deletebackup]
  smartrollback:
    description: Smart rollback with CoreProtect integration
    usage: /smartrollback <time> [user] [radius]
    permission: serverbackup.smartrollback
    aliases: [sr, srollback]

permissions:
  serverbackup.*:
    description: Gives access to all ServerBackup commands
    children:
      serverbackup.backup: true
      serverbackup.list: true
      serverbackup.restore: true
      serverbackup.delete: true
      serverbackup.smartrollback: true
  serverbackup.backup:
    description: Allows creating backups
    default: op
  serverbackup.list:
    description: Allows listing backups
    default: op
  serverbackup.restore:
    description: Allows restoring from backups
    default: op
  serverbackup.delete:
    description: Allows deleting backups
    default: op
  serverbackup.smartrollback:
    description: Use smart rollback with CoreProtect
    default: op
